// This file is generated by kconfig_compiler from kdiamond.kcfg.
// All changes you do to this file will be lost.
#ifndef SETTINGS_H
#define SETTINGS_H

#include <kconfigskeleton.h>
#include <kdebug.h>

class Settings : public KConfigSkeleton
{
  public:

    static Settings *self();
    ~Settings();

    /**
      Set Play an untimed game.
    */
    static
    void setUntimed( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "Untimed" ) ))
        self()->mUntimed = v;
    }

    /**
      Get Play an untimed game.
    */
    static
    bool untimed()
    {
      return self()->mUntimed;
    }

  protected:
    Settings();
    friend class SettingsHelper;


    // Preferences
    bool mUntimed;

  private:
};

#endif

